# Default settings
defaults: &defaults
  working_directory: ~/project
  docker:
    - image: circleci/node:10.16.3

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Installing Node Modules"
          command: npm i
      - save_cache:
          paths:
            - node_modules
          key: node-dependencies-{{ checksum "package.json" }}
  lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Typescript Linting"
          command: npm run lint
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Running Jest Tests"
          command: |
            npm test -- --ci
            find coverage -name "lcov.info" -exec cat {} \; | ./node_modules/coveralls/bin/coveralls.js
      - store_test_results:
          path: coverage/
      - store_artifacts:
          path: coverage/
  format-check:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Checking File Formatting"
          command: npm run format:check
  build-core:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: node-dependencies-{{ checksum "package.json" }}
      - run:
          name: "Building Core"
          command: npm run build
workflows:
  version: 2
  build-and-test:
    jobs:
      - install
      - lint:
          requires:
            - install
      - test:
          requires:
            - install
      - format-check:
          requires:
            - install
      - build-core:
          requires:
            - install
